release:
  name: "release-2026-06-02"
  target: "promotion"

solutions:
  - name: "MainSolution"
    order: 10
    has_env_settings: true

  - name: "SurveysSolution"
    order: 20
    has_env_settings: true